# Generated by Django 6.0.3 on 2026-03-09 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('podcast_episode', 'Podcast episode'), ('video', 'Video'), ('article', 'Article'), ('social_post', 'Social post'), ('link', 'Link')], default='link', max_length=32)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('is_public', models.BooleanField(default=True)),
                ('original_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('shared_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('short_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-shared_at', '-id'),
            },
        ),
    ]
