# Generated by Django 6.0.3 on 2026-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='enrichment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='original_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
