# Generated by Django 6.0.3 on 2026-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_item_author_item_enrichment_error_item_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='long_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='summary_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='summary_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
