# Generated by Django 6.0.3 on 2026-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_item_long_summary_item_summary_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='summary_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='summary_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
