# Generated by Django 6.0.3 on 2026-03-11 09:15

from django.db import migrations, models


def initialize_transcript_state(apps, schema_editor) -> None:
    Item = apps.get_model("archive", "Item")
    transcribable_kinds = {"podcast_episode", "video"}

    Item.objects.filter(transcript__gt="").update(
        transcript_status="complete",
        transcript_generated=True,
    )
    Item.objects.exclude(transcript__gt="").filter(
        models.Q(kind__in=transcribable_kinds)
        | ~models.Q(audio_url="")
        | ~models.Q(media_url="")
    ).update(transcript_status="pending")
    Item.objects.exclude(transcript__gt="").exclude(
        models.Q(kind__in=transcribable_kinds)
        | ~models.Q(audio_url="")
        | ~models.Q(media_url="")
    ).update(transcript_status="complete")


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_item_summary_retry_at_item_summary_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='long_summary_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='short_summary_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tags_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='transcript_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='transcript_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='transcript_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.RunPython(initialize_transcript_state, migrations.RunPython.noop),
    ]
