# Generated by Django 6.0.3 on 2026-03-13 17:02

from django.db import migrations, models


def initialize_article_audio_state(apps, schema_editor) -> None:
    Item = apps.get_model("archive", "Item")

    Item.objects.filter(article_audio_artifact_path__gt="").update(
        article_audio_status="complete",
        article_audio_generated=True,
    )
    Item.objects.exclude(article_audio_artifact_path__gt="").filter(kind="article").update(
        article_audio_status="pending"
    )
    Item.objects.exclude(article_audio_artifact_path__gt="").exclude(kind="article").update(
        article_audio_status="complete"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_item_long_summary_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='article_audio_artifact_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='article_audio_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='article_audio_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='article_audio_job_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='article_audio_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='article_audio_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=16),
        ),
        migrations.RunPython(initialize_article_audio_state, migrations.RunPython.noop),
    ]
