# Generated by Django 6.0.3 on 2026-03-13 18:26

from django.db.models import Q
from django.db import migrations, models


AUDIO_SUFFIXES = (".mp3", ".m4a", ".aac", ".ogg", ".opus", ".wav")


def queue_existing_archivable_audio(apps, schema_editor) -> None:
    Item = apps.get_model("archive", "Item")

    audio_source_query = Q(audio_url__gt="")
    for suffix in AUDIO_SUFFIXES:
        audio_source_query |= (
            Q(original_url__iendswith=suffix)
            | Q(media_url__iendswith=suffix)
            | Q(audio_url__iendswith=suffix)
        )

    (
        Item.objects.filter(
            archived_audio_path="",
            media_archive_status="complete",
        )
        .filter(Q(kind="podcast_episode") | audio_source_query)
        .update(media_archive_status="pending")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_item_article_audio_artifact_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived_audio_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_audio_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_audio_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='media_archive_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='media_archive_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='media_archive_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='media_archive_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=16),
        ),
        migrations.RunPython(queue_existing_archivable_audio, migrations.RunPython.noop),
    ]
