# Generated by Django 6.0.3 on 2026-03-14 13:03

from django.db import migrations, models
from urllib.parse import urlparse


VIDEO_SUFFIXES = (".mp4", ".m4v", ".mov", ".webm")


def queue_existing_archivable_video(apps, schema_editor) -> None:
    Item = apps.get_model("archive", "Item")
    candidate_ids: list[int] = []

    for item in Item.objects.filter(
        archived_audio_path="",
        media_archive_status="complete",
    ).only("id", "original_url", "media_url"):
        urls = (item.original_url or "", item.media_url or "")
        if any(urlparse(url).path.lower().endswith(VIDEO_SUFFIXES) for url in urls if url):
            candidate_ids.append(item.id)

    if candidate_ids:
        Item.objects.filter(id__in=candidate_ids).update(media_archive_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_item_archived_audio_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived_video_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_video_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_video_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(queue_existing_archivable_video, migrations.RunPython.noop),
    ]
