# Generated by Django 6.0.3 on 2026-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_item_archived_video_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='classification_rule',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='podcast_feed_policy',
            field=models.CharField(choices=[('auto', 'Automatic'), ('include', 'Include'), ('exclude', 'Exclude')], default='auto', max_length=16),
        ),
    ]
