# Generated by Django 6.0.3 on 2026-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_item_classification_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification_engine_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
