# Generated by Django 6.0.3 on 2026-03-16 11:30

from django.db import migrations


CREATE_FTS_SQL = """
CREATE VIRTUAL TABLE archive_item_fts USING fts5(
    title,
    short_summary,
    long_summary,
    notes,
    transcript,
    content='archive_item',
    content_rowid='id'
);
"""


POPULATE_FTS_SQL = """
INSERT INTO archive_item_fts(rowid, title, short_summary, long_summary, notes, transcript)
SELECT id, title, short_summary, long_summary, notes, transcript
FROM archive_item;
"""


CREATE_INSERT_TRIGGER_SQL = """
CREATE TRIGGER archive_item_ai AFTER INSERT ON archive_item BEGIN
    INSERT INTO archive_item_fts(rowid, title, short_summary, long_summary, notes, transcript)
    VALUES (new.id, new.title, new.short_summary, new.long_summary, new.notes, new.transcript);
END;
"""


CREATE_DELETE_TRIGGER_SQL = """
CREATE TRIGGER archive_item_ad AFTER DELETE ON archive_item BEGIN
    INSERT INTO archive_item_fts(archive_item_fts, rowid, title, short_summary, long_summary, notes, transcript)
    VALUES ('delete', old.id, old.title, old.short_summary, old.long_summary, old.notes, old.transcript);
END;
"""


CREATE_UPDATE_TRIGGER_SQL = """
CREATE TRIGGER archive_item_au AFTER UPDATE ON archive_item BEGIN
    INSERT INTO archive_item_fts(archive_item_fts, rowid, title, short_summary, long_summary, notes, transcript)
    VALUES ('delete', old.id, old.title, old.short_summary, old.long_summary, old.notes, old.transcript);
    INSERT INTO archive_item_fts(rowid, title, short_summary, long_summary, notes, transcript)
    VALUES (new.id, new.title, new.short_summary, new.long_summary, new.notes, new.transcript);
END;
"""


DROP_INSERT_TRIGGER_SQL = "DROP TRIGGER IF EXISTS archive_item_ai;"
DROP_DELETE_TRIGGER_SQL = "DROP TRIGGER IF EXISTS archive_item_ad;"
DROP_UPDATE_TRIGGER_SQL = "DROP TRIGGER IF EXISTS archive_item_au;"
DROP_FTS_SQL = "DROP TABLE IF EXISTS archive_item_fts;"


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0010_item_classification_engine_version"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_FTS_SQL,
            reverse_sql=DROP_FTS_SQL,
        ),
        migrations.RunSQL(
            sql=POPULATE_FTS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=CREATE_INSERT_TRIGGER_SQL,
            reverse_sql=DROP_INSERT_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=CREATE_DELETE_TRIGGER_SQL,
            reverse_sql=DROP_DELETE_TRIGGER_SQL,
        ),
        migrations.RunSQL(
            sql=CREATE_UPDATE_TRIGGER_SQL,
            reverse_sql=DROP_UPDATE_TRIGGER_SQL,
        ),
    ]
