# Generated by Django 6.0.3 on 2026-07-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_item_processing_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('podcast_episode', 'Podcast episode'), ('video', 'Video'), ('article', 'Article'), ('social_post', 'Social post'), ('quote', 'Quote'), ('link', 'Link')], default='link', max_length=32),
        ),
    ]
