# Generated by Django 6.0.3 on 2026-10-06 20:02

import hashlib
from urllib.parse import unquote, urlsplit, urlunsplit

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# Frozen copy of archive.urlkeys.normalize_capture_url as of this migration.
_DEFAULT_PORTS = {"http": 80, "https": 443}
_TRACKING_PARAMS = frozenset({"fbclid", "gclid", "mc_cid", "mc_eid"})


def _is_tracking_param(raw_name):
    name = unquote(raw_name.replace("+", " ")).lower()
    return name.startswith("utm_") or name in _TRACKING_PARAMS


def _normalize_capture_url(url):
    parts = urlsplit(url.strip())
    scheme = parts.scheme.lower()
    host = (parts.hostname or "").lower()
    if ":" in host:
        host = f"[{host}]"
    try:
        port = parts.port
    except ValueError:
        port = None
    netloc = host
    if port is not None and _DEFAULT_PORTS.get(scheme) != port:
        netloc = f"{host}:{port}"
    if parts.username is not None:
        userinfo = parts.username
        if parts.password is not None:
            userinfo = f"{userinfo}:{parts.password}"
        netloc = f"{userinfo}@{netloc}"
    path = parts.path or "/"
    query = "&".join(
        piece
        for piece in parts.query.split("&")
        if not (piece and _is_tracking_param(piece.split("=", 1)[0]))
    )
    return urlunsplit((scheme, netloc, path, query, ""))


def backfill_capture_keys(apps, schema_editor):
    """Fingerprint every item and give each URL's newest item the capture key.

    Existing duplicates are kept as they are; older copies only get url_key, so future
    captures are compared against the newest copy and the unique index can be added.
    """
    Item = apps.get_model("archive", "Item")
    holders = {}
    rows = Item.objects.order_by("shared_at", "id").values_list("id", "original_url")
    for item_id, original_url in rows.iterator():
        url_key = hashlib.sha256(_normalize_capture_url(original_url).encode("utf-8")).hexdigest()
        Item.objects.filter(pk=item_id).update(url_key=url_key)
        holders[url_key] = item_id
    for url_key, item_id in holders.items():
        Item.objects.filter(pk=item_id).update(capture_key=url_key)


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_alter_item_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('url_key', models.CharField(help_text='url_key of the URL sent with the first request using this key.', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='capture_key',
            field=models.CharField(blank=True, editable=False, help_text='Equal to url_key on the newest item for a URL; NULL on older copies.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='url_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256 of the normalised URL, used to recognise repeated captures.', max_length=64, null=True),
        ),
        migrations.RunPython(backfill_capture_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('capture_key__isnull', False)), fields=('capture_key',), name='archive_item_unique_capture_key'),
        ),
        migrations.AddField(
            model_name='captureidempotencykey',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='archive.item'),
        ),
    ]
